# Generated by Django 4.2 on 2023-04-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
    ]
