# Generated by Django 4.2 on 2023-04-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0002_room_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room',
        ),
    ]
